name: Use Secrets
on:
  push:
    paths:
      - ".github/workflows/use-secrets.yml"

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/repo_secret_action@main
      - name: Grade use-secrets activity run
        id: check-secrets
        uses: ./.github/actions/check-secrets-action'
        with:
          secrets-context: ${{toJSON(secrets)}}
